# Generated by Django 3.2 on 2022-01-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='author',
        ),
    ]
