# Generated by Django 4.2.13 on 2024-07-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(default=None),
        ),
    ]
