# Generated by Django 4.2.13 on 2024-07-12 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_product_brand_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='author',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
        migrations.AddField(
            model_name='order',
            name='arrive_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='order',
            name='brand',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='market_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.IntegerField(default=None),
        ),
    ]
